// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Wu08AGDTTQShPY9Pjs7CR8OySTrHWi0',
    appId: '1:904733751924:web:b15d9349d2a935db38ef21',
    messagingSenderId: '904733751924',
    projectId: 'chatapp-2f21a',
    authDomain: 'chatapp-2f21a.firebaseapp.com',
    storageBucket: 'chatapp-2f21a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBknUwWeSj-yn9OlUVO-3bzOE_O3foLhFc',
    appId: '1:904733751924:android:5848ad2b91e6cd5038ef21',
    messagingSenderId: '904733751924',
    projectId: 'chatapp-2f21a',
    storageBucket: 'chatapp-2f21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUZiGsB1CHpyce0TPrsYwmESv5_ljEl4',
    appId: '1:904733751924:ios:d7dfb9395f3bb16238ef21',
    messagingSenderId: '904733751924',
    projectId: 'chatapp-2f21a',
    storageBucket: 'chatapp-2f21a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUZiGsB1CHpyce0TPrsYwmESv5_ljEl4',
    appId: '1:904733751924:ios:d7dfb9395f3bb16238ef21',
    messagingSenderId: '904733751924',
    projectId: 'chatapp-2f21a',
    storageBucket: 'chatapp-2f21a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Wu08AGDTTQShPY9Pjs7CR8OySTrHWi0',
    appId: '1:904733751924:web:e5f6970c413b9b6138ef21',
    messagingSenderId: '904733751924',
    projectId: 'chatapp-2f21a',
    authDomain: 'chatapp-2f21a.firebaseapp.com',
    storageBucket: 'chatapp-2f21a.firebasestorage.app',
  );

}